#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
#pkill sxhkd > /dev/null && sxhkd &



#bspc monitor HDMI-0 -d main dev games
#bspc monitor DP-4 -d web music docs 
test -f ~/.config/bspwm/bspwmrc.local && . ~/.config/bspwm/bspwmrc.local

bspc config border_width         0
bspc config window_gap          12
bspc config top_padding					22

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bsp-layout set tall main

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a polybar layer=below
bspc rule -a mordhau desktop=games
bspc rule -a steam desktop=games
bspc rule -a google-chrome desktop=2
bspc rule -a Google-chrome desktop=2
bspc rule -a chrome desktop=2
bspc rule -a Chrome desktop=2

nitrogen --restore &
pgrep -x compton 2>&1 >/dev/null || compton -b &
nm-applet & 

#xinput set-prop "Logitech G502 HERO Gaming Mouse" "libinput Accel Speed" -0.125
#xinput set-prop "Logitech G502 HERO Gaming Mouse" "libinput Accel Profile Enabled" 0, 1
set xkbmap -option caps:escape
~/.config/polybar/bspwm_launch.sh & 
